### ISSUE TITLE
Set up a Notebook with EDLogin (netrc)

### ISSUE THREAD

**Issue by virdi** [NASA-Openscapes/common#12]
We need a common method for login credential, reusable component

**Comment by virdi** [comment]
Duplicate of #1

**Comment by jules32** [comment]
Bringing links from issue #1 and closing it, since it's flagged as duplicate

From Erin's original #1 :

[[PODAA AGU tutorial with EarthData login materials](https://github.com/NASA-Openscapes/AGU-2020/blob/main/Part-II/01_sst_shpfile/AGU_tutorial1_shp_search.ipynb)] 

Create common netrc file setup tutorial based on [HLS tutorial](https://github.com/NASA-Openscapes/lpdaac_hls_tutorial) and others

**Comment by jules32** [comment]
Following @cpkrehbiel's success [adding a .ipynb to the jupyterbook](https://nasa-openscapes.github.io/openscapes_jupyterbook_test/discovery/Navigate_CMR_STAC.html), I added a [placeholder/stub .ipynb chapter too](https://nasa-openscapes.github.io/openscapes_jupyterbook_test/getting_started/earthdata_login_test.html), linking to Christine's [post on Jupyter Discourse](https://discourse.jupyter.org/t/how-do-i-properly-protect-my-data-access-passwords-not-jupyter-tokens-passwords-on-3rd-party-jupyter-hub-services/9277).

**Comment by jjmcnelis** [comment]
Perhaps check out this example: https://github.com/podaac/ECCO/blob/main/Data_Access/local_bulk_download_and_open_in_py3.ipynb

Could be a starting point (or stopping point depending on what we want to accomplish).

**Comment by jules32** [comment]
Thanks @jjmcnelis. I've added the netrc parts of that as a .ipynb file. Would you be able to review when you have a chance and even add more prose/description or outline what would be useful as an intro here?

https://nasa-openscapes.github.io/openscapes_jupyterbook_test/getting_started/podaac-ecco-netrc.html

**Comment by jjmcnelis** [comment]
> Thanks @jjmcnelis. I've added the netrc parts of that as a .ipynb file. Would you be able to review when you have a chance and even add more prose/description or outline what would be useful as an intro here?
> 
> https://nasa-openscapes.github.io/openscapes_jupyterbook_test/getting_started/podaac-ecco-netrc.html
> 

Sure thing

Btw it looks like you added my example lines to your netrc a few times @jules32 

The ipynb shoulda made a backup copy of the original tho. See the very first part if you need to revert

**Comment by jules32** [comment]
Thanks @jjmcnelis, I've just copy-pasted your notebook and re-rendered several times. There should be a way to have code display but not run each time we render. 

I actually didn't look at the netrc I produced, because I was just focused on the book structure. Would you be able to write up more documentation and narrative about what researchers should do if they needed to revert, and why?

**Comment by jules32** [comment]
Closing this here, see https://github.com/NASA-Openscapes/earthdata-cloud-cookbook/issues/44 for more up-to-date activity
